AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Expense Claim Approval System

Resources:
  # 1. The Lambda Function
  ApproveClaimsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/approve-claims.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64
#      Policies:
#        # Give the Lambda permission to call Step Functions
#        - StepFunctionsExecutionStatusPolicy:
#            StateMachineArn: !Ref ClaimsApprovalStateMachine
      Events:
        # 2. The API Gateway (Implicitly created)
        ApproveApi:
          Type: Api
          Properties:
            Path: /approve
            Method: get
        RejectApi:
          Type: Api
          Properties:
            Path: /reject
            Method: get

  # 3. The Step Function (State Machine)
  ClaimsApprovalStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      # Keep your ASL in a separate file for cleanliness
      DefinitionUri: statemachine/claims_approval_process.asl.json
      DefinitionSubstitutions:
        # This replaces placeholders in your ASL with real ARNs
        SnsTopicArn: !Ref ClaimsApprovalTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ClaimsApprovalTopic.TopicName

  # 4. The SNS Topic
  ClaimsApprovalTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ClaimsApprovalTopic

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"