AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Expense Claim Approval System

Parameters:
  AppStage:
    Type: String
    Default: Prod

Resources:
  # Step function to orchestrate the whole claims submission and approval flow
  ClaimsApprovalStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: statemachines/claims_approval_process.asl.json
      DefinitionSubstitutions:
        SNS_TOPIC_ARN: !Ref ClaimsNotificationTopic
        APPROVAL_API_BASE_URL: !Sub "https://${ApprovalApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}"
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt ClaimsNotificationTopic.TopicName
      Events:
        SubmitApi:
          Type: Api
          Properties:
            Path: /submit
            Method: post
            RestApiId: !Ref SubmissionApi

  # API Gateway to submit claims via triggering the ClaimsApprovalStateMachine
  SubmissionApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: SubmissionApi
      StageName: !Ref AppStage

  # Lambda function to handle manual approvals and rejections
  ApproveClaimsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: functions/handlers/approve-claims.handler
      Runtime: nodejs24.x
      Architectures:
        - arm64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - states:SendTaskSuccess
              Resource: "*"
      Events:
        ApproveApi:
          Type: Api
          Properties:
            Path: /approve
            Method: get
            RestApiId: !Ref ApprovalApi
        RejectApi:
          Type: Api
          Properties:
            Path: /reject
            Method: get
            RestApiId: !Ref ApprovalApi

  # API gateway to trigger ApproveClaimsFunction
  ApprovalApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ApprovalApi
      StageName: !Ref AppStage

  # SNS topic to notify when claims submitted, approved and rejected
  ClaimsNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ClaimsNotificationTopic

Outputs:
  SubmitApiUrl:
    Description: "Submission API Gateway URL"
    Value: !Sub "https://${SubmissionApi}.execute-api.${AWS::Region}.amazonaws.com/${AppStage}/"